syntax enable     
set ruler
set backspace=indent,eol,start 
set showmatch	  

set hlsearch	  
set ignorecase	  
set smartcase	  
set incsearch	  

set expandtab	  
set smartindent	  
set smarttab	  

set background=dark

